---
name: AntiServerStop
version: 1.0.2
main: NhanAZ\AntiServerStop\Main
api: 5.0.0
author: NhanAZ
website: https://github.com/NhanAZ
src-namespace-prefix: NhanAZ\AntiServerStop
description: "The operator won't be able to stop your server if they don't have the password!"

commands:
  stop:
    description: "Stops the server"
    usage: "/stop <password>"
    permission: antiserverstop.command
permissions:
  antiserverstop.command:
    description: "Allows the user to stop the server"
    default: op
...
